apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mccp
    app.kubernetes.io/component: cluster-bootstrap-controller
    control-plane: controller-manager
  name: metrics
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: metrics