apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - image: enekofb/metrics:latest
        name: metrics
        volumeMounts:
          - name: config
            mountPath: /config
        env:
          - name: CONFIG_PATH
            value: "/config/config.yaml"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github
                key: GITHUB_TOKEN
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
        - name: config
          configMap:
            name: metrics
            items:
              - key: config.yaml
                path: config.yaml