apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - image: enekofb/metrics:latest
        name: metrics
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              configMapKeyRef:
                name: metrics
                key: GITHUB_TOKEN
          - name: GITHUB_BUG_LABEL
            valueFrom:
              configMapKeyRef:
                name: metrics
                key: GITHUB_BUG_LABEL
          - name: GITHUB_OWNER
            valueFrom:
              configMapKeyRef:
                name: metrics
                key: GITHUB_OWNER
          - name: GITHUB_REPO
            valueFrom:
              configMapKeyRef:
                name: metrics
                key: GITHUB_REPO
          - name: GITHUB_TEAM_LABEL
            valueFrom:
              configMapKeyRef:
                name: metrics
                key: GITHUB_TEAM_LABEL

        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
