apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  labels:
    app: metrics
    release: prometheus-prometheus
spec:
  selector:
    matchLabels:
      app: metrics
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics