apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
    release: prometheus-prometheus
  name: metrics
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: metrics